Repository COINKIRI/Coinkiri-android, pull requests merged in 2024-08, with the labels that each got.

#2 프로젝트 기본 세팅
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coinkiri/coinkiri/CoinkiriApplication.kt
  app/src/main/java/com/coinkiri/coinkiri/MainActivity.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/theme/Color.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/theme/Theme.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🔧 chore, ⚙️ setting

#12 앱 커스텀 폰트 추가
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Theme.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Type.kt
  app/src/main/res/font/yangjin_regular.otf
Labels: ✨ feat, ♻️ refactor

#13 메인화면 ui 구현
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Type.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainActivity.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/component/CoinTalkTabCard.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/component/MainTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/component/MenuTabCard.kt
  app/src/main/res/drawable/btc.png
  app/src/main/res/drawable/img_main_coin_book.png
  app/src/main/res/drawable/img_main_coin_price.png
  app/src/main/res/drawable/img_main_talk.png
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#15 로그인 화면 ui 구현
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Color.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/login/LoginScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/component/LoginBtn.kt
  app/src/main/res/drawable/img_coinkiri_app_icon.xml
  app/src/main/res/drawable/img_login_kakao.xml
  app/src/main/res/drawable/img_login_naver.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#16 시세조회화면 ui 구성
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinScreenTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinSortBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#17 코인톡 화면 UI 구현
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/component/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/component/button/JoinChatButton.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/component/common/CoinInfo.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/component/topappbar/CoinkiriTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Color.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talk/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/talk/TalkScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talk/component/CoinTalkItem.kt
Labels: ✨ feat

#20 스플래시 화면 UI 구성
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/SplashScreen.kt
Labels: ✨ feat

#18 코인톡방 UI 구성
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/ChatScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/ChatContent.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/ChatInputField.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/ChatScreenTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/SelectedCoinInfo.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/TextBubble.kt
  gradle/libs.versions.toml
Labels: ✨ feat

#22 화면 navigation 구현
  app/build.gradle.kts
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/HomeScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/component/CoinTalkTabCard.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/component/MenuTabCard.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainActivity.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/Route.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/ScreenNavigator.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/component/MainTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/mypage/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/ProfileScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/SplashScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talk/TalkScreen.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🔧 chore, ✨ feat

#25 카카오 로그인 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coinkiri/coinkiri/CoinkiriApplication.kt
  app/src/main/java/com/coinkiri/coinkiri/core/datastore/TokenDataStore.kt
  app/src/main/java/com/coinkiri/coinkiri/core/datastore/TokenDataStoreImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/core/datastore/di/DataStoreModule.kt
  app/src/main/java/com/coinkiri/coinkiri/core/datastore/di/TokenDataStoreModule.kt
  app/src/main/java/com/coinkiri/coinkiri/core/network/BaseResponse.kt
  app/src/main/java/com/coinkiri/coinkiri/core/network/NetworkModule.kt
  app/src/main/java/com/coinkiri/coinkiri/core/network/OauthInterceptor.kt
  app/src/main/java/com/coinkiri/coinkiri/core/network/Qualifier.kt
  app/src/main/java/com/coinkiri/coinkiri/core/network/StringExtension.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/datasource/LoginDataSource.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/datasourceimpl/LoginDataSourceImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/di/DataSourceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/di/RepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/di/ServiceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/dto/request/LoginRequestDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/dto/response/LoginResponseDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/repositoryimpl/LoginRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/login/service/LoginService.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/datasource/ReissueTokenDataSource.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/datasourceimpl/ReissueTokenDataSourceImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/di/DataSourceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/di/ReissueTokenRepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/di/ServiceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/repositoryimpl/ReissueTokenRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/response/ReissueTokenResponseDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/reissuetoken/service/ReissueTokenService.kt
  app/src/main/java/com/coinkiri/coinkiri/data/token/di/TokenRepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/token/repositoryimpl/TokenRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/login/entity/reponse/LoginResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/login/entity/request/LoginRequestEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/login/repository/LoginRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/reissuetoken/entity/ReissueTokenResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/reissuetoken/repository/ReissueTokenRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/token/repository/TokenRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/designsystem/theme/Color.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/LoginScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/LoginSideEffect.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/LoginViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/component/LoginBtn.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainActivity.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/ScreenNavigator.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/SplashScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/SplashSideEffect.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/SplashViewModel.kt
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🔧 chore, ✨ feat

#28 코인톡방 화면 코드 구조 및 ui layout 리펙토링
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/component/bottombar/BottomTextField.kt
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/component/button/JoinChatButton.kt
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/component/common/CoinInfo.kt
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/component/topappbar/CoinkiriTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/theme/Color.kt
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/theme/Theme.kt
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/theme/Type.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinScreenTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinSortBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/HomeScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/component/CoinTalkTabCard.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/component/MenuTabCard.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/LoginScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/component/LoginBtn.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainActivity.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/ProfileScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/component/FirstSettingList.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/component/ProfileImg.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/component/SecondSettingList.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/component/ThirdSettingList.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/SplashScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talk/TalkScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talk/component/CoinTalkItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/ChatScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/TalkDetailScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/ChatContent.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/ChatInputField.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/ChatScreenTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/SelectedCoinInfo.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/SelectedCoinInfoItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/talkdetail/component/TextBubble.kt
  app/src/main/res/drawable/ic_arrow_circle_up.xml
Labels: ♻️ refactor

#32 server에서 coin 목록리스트 받아 ui 연결
  app/build.gradle.kts
  app/src/main/java/com/coinkiri/coinkiri/core/util/byteArrayToPainter.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/datasource/CoinDataSource.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/datasourceimpl/CoinDataSourceImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/di/DataSourceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/di/RepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/di/ServiceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/dto/response/CoinResponseDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/mapper/CoinMapper.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/repositoryimpl/CoinRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/service/CoinService.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/CoinResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/repository/CoinRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/usecase/GetCoinListUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinScreenTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  gradle/libs.versions.toml
Labels: 🔧 chore, ✨ feat
