Repository COINKIRI/Coinkiri-android, pull requests merged in 2024-09, with the labels that each got.

#35 업비트 웹소켓을 통한 실시간 코인가격데이터 수신기능 추가
  app/build.gradle.kts
  app/src/main/java/com/coinkiri/coinkiri/core/network/NetworkModule.kt
  app/src/main/java/com/coinkiri/coinkiri/core/network/Qualifier.kt
  app/src/main/java/com/coinkiri/coinkiri/core/util/Formatter.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/mapper/CoinMapper.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/repositoryimpl/CoinRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/datasource/TickerDataSource.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/datasourceimpl/TickerDataSourceImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/di/DataSourceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/di/RepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/di/ServiceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/dto/request/TickerRequestDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/dto/response/TickerResponseDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/mapper/TickerMapper.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/repositoryimpl/TickerRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/service/TickerService.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/MergedCoinTickerEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/request/TickerRequestEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/response/CoinResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/response/TickerResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/repository/CoinRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/repository/TickerRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/usecase/GetCoinListUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/usecase/GetTicketsUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
Labels: ✨ feat

#36 코인시세 상세보기 화면 ui 구성
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/CoinScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coindetail/.gitkeep
  app/src/main/java/com/coinkiri/coinkiri/ui/coindetail/CoinDetailScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coindetail/component/CoinChartItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coindetail/component/CoinDetailInfoItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coindetail/component/CoinTalkButton.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/ScreenNavigator.kt
Labels: ✨ feat

#39 코인상세정보 코인끼리 서버로부터 받아오도록 구현
  app/build.gradle.kts
  app/src/main/java/com/coinkiri/coinkiri/core/navigation/Route.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/datasource/CoinDataSource.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/datasourceimpl/CoinDataSourceImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/dto/response/CoinDetailResponseDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/mapper/CoinDetailMapper.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/repositoryimpl/CoinRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/coin/service/CoinService.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/MergedCoinTickerEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/entity/response/CoinDetailResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/repository/CoinRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/usecase/GetCoinDetailInfoUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coindetail/CoinDetailScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coindetail/CoinDetailViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coinlist/CoinListScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coinlist/CoinListViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinChartItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinDetailInfoItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinTalkButton.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/model/CoinDetailModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/model/CoinModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/navigation/CoinNavigation.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/HomeScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/navigation/LoginNavigation.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/Route.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/ScreenNavigator.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/splash/navigation/SplashNavigation.kt
  gradle/libs.versions.toml
Labels: 🔧 chore, ✨ feat, ♻️ refactor

#38 서버에서 유저정보를 받아 ui연결 (미해결)
  app/build.gradle.kts
  app/src/main/java/com/coinkiri/coinkiri/data/user/datasource/UserDataSource.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/datasourceimpl/UserDataSourceImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/di/DataSourceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/di/RepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/di/ServiceModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/dto/UserResponseDto.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/mapper/UserMapper.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/data/user/service/UserService.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/user/entity/UserEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/user/repository/UserRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/user/usecase/GetUserInfoUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/ProfileScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/component/UserInfoItem.kt
Labels: 🐞 bug, 🔧 chore, ✨ feat

#44 코인 상세정보 화면 차트부분 ui구현
  app/build.gradle.kts
  app/src/main/java/com/coinkiri/coinkiri/core/navigation/Route.kt
  app/src/main/java/com/coinkiri/coinkiri/core/util/CustomMarkerView.kt
  app/src/main/java/com/coinkiri/coinkiri/core/util/Formatter.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/di/RepositoryModule.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/mapper/TickerMapper.kt
  app/src/main/java/com/coinkiri/coinkiri/data/ticker/repositoryimpl/TickerRepositoryImpl.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/repository/TickerRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/coin/usecase/GetTicketsUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/ticker/entity/request/TickerRequestEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/ticker/entity/response/TickerDetailResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/ticker/entity/response/TickerResponseEntity.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/ticker/repository/TickerRepository.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/ticker/usecase/GetTickerDetailUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/ticker/usecase/GetTickersUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coindetail/CoinDetailScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coindetail/CoinDetailViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coinlist/CoinListScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/coinlist/CoinListViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinChartItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinDetailInfoItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/component/CoinItem.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/model/TickerDetailModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/coin/navigation/CoinNavigation.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/MainScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/main/ScreenNavigator.kt
  app/src/main/res/drawable/ic_coin_detail_marker.xml
  app/src/main/res/layout/custom_marker_view.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🔧 chore, ✨ feat, ♻️ refactor

#43 내정보 수정화면 ui구현
  app/src/main/java/com/coinkiri/coinkiri/core/designsystem/component/topappbar/CoinkiriTopBar.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profilemodify/ProfileModifyScreen.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profilemodify/component/ProfileModifyItem.kt
Labels: ✨ feat

#49 로그인, 토큰 usecase 추가
  app/src/main/java/com/coinkiri/coinkiri/domain/login/usecase/PostLoginUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/token/usecase/ClearTokenUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/domain/token/usecase/SetTokenUseCase.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/login/LoginViewModel.kt
  app/src/main/java/com/coinkiri/coinkiri/ui/profile/ProfileViewModel.kt
Labels: ✨ feat, ♻️ refactor
